---
- name: get ipa server facts
  hosts: ipa01.linux.lab
  become: false
  gather_facts: true

  tasks:
  - name: hello
    debug:
      msg: 'hello from {{ inventory_hostname }}'

- name: update windows and configure ad domain
  hosts: ad01.windows.lab
  become: false
  remote_user: Administrator
  gather_facts: true

  tasks:
  - name: add SRV record _kerberos._tcp.{{ ad_domain }} to ad dns
    win_shell: >-
      if ( -not ( Resolve-DnsName -Name _kerberos._udp.dc._msdcs.{{ ad_domain }} -Type SRV )) {
      Add-DnsServerResourceRecord -Srv -Name "_kerberos._udp.dc" -ZoneName "_msdcs.{{ ad_domain }}"
      -DomainName "{{ inventory_hostname }}" -Priority 0 -Weight 100 -Port 88
      }

  - name: set masterservers var
    set_fact:
      masterservers: "{{ hostvars[groups['ipaserver'][0]]['ansible_default_ipv4']['address'] }}"

  - name: add conditional forwarder to ad dns
    win_shell: >-
      if ( -not ( Resolve-DnsName -Name {{ groups['ipaserver'][0] }} -Type SRV )) {
      Add-DnsServerConditionalForwarderZone -MasterServers {{ masterservers }} -Name {{ ipaserver_domain }}
      }
