all:
  hosts:
    ad01.windows.lab:
      ansible_host: 192.168.122.99
    ipa01.linux.lab:
      ansible_host: 192.168.122.2
  children:
    ipaserver:
      hosts:
        ipa01.linux.lab:
    windows:
      hosts:
        ad01.windows.lab:
