---
- name: setup ipa server
  hosts: ipa01.linux.lab
  become: false
  gather_facts: true

  tasks:
  - name: ensure the dnsforwardzone has an entry for the ms-ad-dns
    ipadnsforwardzone:
      ipaadmin_principal: "{{ ipaadmin_principal }}"
      ipaadmin_password: "{{ ipaadmin_password }}"
      state: present
      name: "{{ ad_domain }}"
      forwarders: "{{ ad_dns_servers }}"
      forwardpolicy: first
      skip_overlap_check: true

  - name: ensure dnsseq validation is off
    lineinfile:
      path: /etc/named.conf
      backrefs: true
      regexp: "(^.*dnssec-validation) yes(;.*$)"
      line: \1 no;
    notify: restart named-pkcs11

  handlers:
  - name: restart named-pkcs11
    service:
      name: named-pkcs11
      state: restarted