---
- name: Install AD Services feature
  win_feature:
    name: AD-Domain-Services
    include_management_tools: 'yes'
    include_sub_features: 'yes'
    state: present

- name: Create new forest
  win_domain:
    dns_domain_name: '{{ ad_domain }}'
    safe_mode_password: '{{ ad_safe_mode_passwd }}'
  register: result

- name: Reboot after creation
  win_reboot:
    msg: "Server config in progress; rebooting..."
  when: result.reboot_required

- name: wait for ad properties query to succeed
  win_shell: Get-ADComputer -Identity "{{ inventory_hostname.split('.')[0] }}" -Properties *
  register: prop_res
  until: prop_res.rc == 0
  retries: 360
  delay: 10